# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit boundHTS.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(boundHTS)
library(kableExtra)



## ----sim_poisson_setup, echo=FALSE, fig.cap="The two-level hierarchical set up of the Poisson simulation. The four child nodes (A, B, C, D) aggregate to the parent node, Total."----
knitr::include_graphics("figures/sim_node_hierarchy.pdf")


## ----echo=FALSE---------------------------------------------------------------
pois_data <- readRDS("data/poisson_2000_AR.RDS") 


## ----poisson-tilt-example, echo=TRUE------------------------------------------

library(ggplot2)
library(boundHTS)

# Forecast origin 
t_idx <- 2000
all_series <- c("Tot","AA", "AB", "BA", "BB")
bottom_series <- c("AA", "AB", "BA", "BB")
z_values <- seq(from = 0, to = c(max(pois_data$Tot)+10))  # support for PMF

# Example: one-step-ahead Poisson predictive means 
# Fit GLM to bottom-level series
fit_list <- lapply(all_series, function(series) {
  tscount::tsglm(as.vector(unlist(pois_data[seq_len(t_idx-1), series])), model = list(past_obs = 1), link = "log")
})

# Predictive means at time t
lambda_pred <- sapply(fit_list, function(fit) {
   predict(fit, n.ahead = 1)$pred
})


## ----poisson convolution,  echo=TRUE------------------------------------------
# Convolution density for total-level series 
conv_density <- Poisson_convolution_density_point_parallel(z_values = z_values,
                                                           lambda_vector = lambda_pred[-1])

# Construct tilted density to match predictive mean 
f_tilted <- tilt_density(mu_theory = lambda_pred[1],
                         y_vals = z_values,
                         f_y = conv_density,
                         discrete = TRUE)



## ----poisson-tilted-plot, fig.cap="The tilted and convoluted density of the top series using Poisson distributed bottom series for a given time point. The dark red colour captures the density of the convolution, the blue represents the tilted denisty and the dashed black line indicates the predictive mean of the top series."----

# Prepare data for plotting 
df_plot <- data.frame(
  y = rep(z_values, 2),
  pmf = c(f_tilted$f_tilted, conv_density),
  Density = rep(c("Tilted density", "Convoluted density"),
                each = length(z_values))
)


# Plot PMFs 
ggplot(df_plot, aes(x = y, y = pmf, fill = Density)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.7) +
  geom_vline(aes(xintercept = lambda_pred[1], linetype = "Predictive mean"), color = "black", lwd=1.2) +
  geom_vline(aes(xintercept = pois_data$Tot[t_idx], linetype = "Observation"), color = "black", lwd = 1.2) +
  labs(x = "Counts", y = "Probability mass", fill = "Mass type", linetype = "Line type") +
  scale_linetype_manual(values = c("Predictive mean" = "dotted", "Observation" = "solid")) +
  theme_minimal() + 
  theme( legend.position = "bottom") +
  scale_fill_brewer(palette = "Set1")



## ----sim_beta_setup, fig.height=5, fig.width=10, fig.cap="The two-level hierarchical set up of the Beta simulation. The two child nodes (AA, AB) aggregate to the parent node, A."----
knitr::include_graphics("figures/beta_sim_hierarchy.pdf")


## ----beta setup, include=FALSE------------------------------------------------
library(ggplot2)
library(dplyr)
library(boundHTS)
library(ExtDist)

t_idx <- 250
weights_bottom <- c(0.75,0.25)
all_series <- c("A","AA","AB")
bottom_series <- c("AA","AB")

beta_sim_data <- boundHTS::beta_sim_data %>%
  arrange(Time) %>%
  mutate(across(all_of(all_series), ~ log(.x/(1-.x)), .names="logit_{.col}"))



## ----fit-models, echo=TRUE----------------------------------------------------
all_series <- c("A","AA","AB")
bottom_series <- c("AA","AB")
n_bottom <- 2

fit_list <- lapply(all_series, function(s) {
  forecast::auto.arima(beta_sim_data[1:(t_idx-1), paste0("logit_", s)])
})



## ----beta-params, echo=TRUE---------------------------------------------------
logit_mu_pred <- sapply(fit_list, predict, h=1)
logit_mu_pred <- as.vector(unlist(logit_mu_pred[1,]))

logit_sim_pred <- lapply(fit_list, function(fit) {
  replicate(5000, simulate(fit, nsim=1, future=TRUE)[[1]])
})

logit_var_pred <- sapply(logit_sim_pred, function(x) var(x))

# Back transform via the Delta method
prop_pred <- 1 / (1 + exp(-logit_mu_pred))
prop_var <- (prop_pred * (1 - prop_pred))^2 * logit_var_pred

# Calculate the beta distribution parameters
top_params <- beta_params(prop_pred[1], sqrt(prop_var[1]))

bottom_params <- list()
for(b in 1:n_bottom) {
  bottom_params[[b]] <- beta_params(prop_pred[b+1], sqrt(prop_var[b+1]))
}



## ----beta convolution, echo=TRUE----------------------------------------------

z_values <- seq(0,1,length.out=1000)

weighted_samps <- array(NA, dim=c(100,100,n_bottom))

for(b in seq_along(bottom_series)) {
  weighted_samps[,,b] <- matrix(ExtDist::rBeta_ab(100*100,
                                    shape1 = bottom_params[[b]][1], 
                                    shape2 = bottom_params[[b]][2],
                                    a=0,
                                    b=weights_bottom[b]), 100, 100)
}

Density_top <- Beta_convolution_density_point_parallel(z_values = z_values,
                                                       alpha_point = bottom_params[[n_bottom]][1],
                                                       beta_point  = bottom_params[[n_bottom]][2],
                                                       weighted_samps = weighted_samps,
                                                       weights = weights_bottom[n_bottom]
                                                       )

f_tilted <- tilt_density(mu_theory = prop_pred[1],
                         y_vals = z_values,
                         f_y = Density_top,
                         discrete=FALSE)



## ----beta-tilted-plot, fig.cap="The tilted and convoluted density of the top series using Beta distributed bottom series nodes for a given time point. The dark red colour captures the density of the convolution, the blue represents the tilted denisty and the dashed black line indicates the predictive mean of the top series."----
df_plot <- data.frame(
  y = rep(z_values,2),
  pdf = c(f_tilted$f_tilted, Density_top),
  Density = rep(c("Tilted density","Convoluted density"), each=length(z_values))
)

ggplot(df_plot, aes(x=y, y=pdf, colour=Density)) +
  geom_line(size=1) +
  geom_vline(aes(xintercept=prop_pred[1], linetype="Predictive mean"), color = "black", lwd=1.2) +
  geom_vline(aes(xintercept = beta_sim_data$A[t_idx], linetype = "Observation"), color = "black", lwd = 1.2) +
    labs(x = "Counts", y = "Probability mass", fill = "Density type", linetype = "Line type") +
  scale_linetype_manual(values = c("Predictive mean" = "dotted", "Observation" = "solid")) +
  theme_minimal() + 
  theme(legend.position = "bottom") +
  scale_colour_brewer(palette = "Set1")



